spring:
  application:
    name: memoring-server

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 600000
  refresh-token-expiration: 7776000000 # 90Ïùº

cloud:
  aws:
    s3:
      bucket: memoring-bucket-579939802977
    region:
      static: ap-northeast-2

openai:
  api-key: ${OPENAI_APIKEY}
